name: smarn
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.5.2 <4.0.0'  # Adjusting the SDK constraint for your project.

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8  # Latest stable version of Cupertino icons
  path_provider: ^2.1.4    # Latest version you're using

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Consider updating this to the latest available version (5.0.0 or above)
  flutter_lints: ^5.0.0  # Update to latest for better linting

flutter:
  uses-material-design: true

  assets:
    - assets/img/
